# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f212d3faabb46eeea3bd8f669151f670eaeacda70126e5a665e492be2c9a42d1784d0a7909f30cc1004cd0da89c43ce7fc158d0f71f7c66d64b72c3e7c62cc0b

test:
  secret_key_base: cecf38af76351e17c1761552f0fcc02d02f11a6c13d392454561214f25638c679d9466433bec8172c9866460d081d8108c1e649ec21e32ddcf1011c852f7ae12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
